# Generated by Django 5.1.1 on 2024-10-11 16:56

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oldbookapp", "0005_alter_customuser_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="profile_images/",
            ),
        ),
    ]
