
categories = [
    'Fiction',
    'Science',
    'History',
    'Biography',
    'Fantasy',
    'Mythology',
    'Thriller',
    'Classic',
    'Dystopian',
    'Science Fiction',
    'Self-Help',
    'Mystery',
    'Health',
]

books = [
    {
        'ISBN': '195153448',
        'Book_Title': 'Classical Mythology',
        'Book_Author': 'Mark P. O. Morford',
        'Description': 'A comprehensive guide to classical mythology.',
        'Year_Of_Publication': '2002',
        'Publisher': 'Oxford University Press',
        'Image_URL': 'http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg',
        'category': 'Mythology',
        'price': 29.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '2005018',
        'Book_Title': 'Clara Callan',
        'Book_Author': 'Richard Bruce Wright',
        'Description': 'A novel about the life of Clara Callan.',
        'Year_Of_Publication': '2001',
        'Publisher': 'HarperFlamingo Canada',
        'Image_URL': 'http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 19.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '60973129',
        'Book_Title': 'Decision in Normandy',
        'Book_Author': 'Carlo D\'Este',
        'Description': 'A detailed account of the Normandy invasion.',
        'Year_Of_Publication': '1991',
        'Publisher': 'HarperPerennial',
        'Image_URL': 'http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 24.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '374157065',
        'Book_Title': 'Flu: The Story of the Great Influenza Pandemic of 1918',
        'Book_Author': 'Gina Bari Kolata',
        'Description': 'An exploration of the 1918 influenza pandemic.',
        'Year_Of_Publication': '1999',
        'Publisher': 'Farrar Straus Giroux',
        'Image_URL': 'http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg',
        'category': 'Health',
        'price': 22.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '393045218',
        'Book_Title': 'The Mummies of Urumchi',
        'Book_Author': 'E. J. W. Barber',
        'Description': 'A fascinating study of mummies from Urumchi.',
        'Year_Of_Publication': '1999',
        'Publisher': 'W. W. Norton & Company',
        'Image_URL': 'http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 27.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '399135782',
        'Book_Title': 'The Kitchen God\'s Wife',
        'Book_Author': 'Amy Tan',
        'Description': 'A story about family and cultural identity.',
        'Year_Of_Publication': '1991',
        'Publisher': 'Putnam Pub Group',
        'Image_URL': 'http://images.amazon.com/images/P/0399135782.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 18.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '425176428',
        'Book_Title': 'What If?: The World\'s Foremost Military Historians Imagine What Might Have Been',
        'Book_Author': 'Robert Cowley',
        'Description': 'Military historians explore alternate history scenarios.',
        'Year_Of_Publication': '2000',
        'Publisher': 'Berkley Publishing Group',
        'Image_URL': 'http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 25.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '671870432',
        'Book_Title': 'PLEADING GUILTY',
        'Book_Author': 'Scott Turow',
        'Description': 'A gripping legal thriller.',
        'Year_Of_Publication': '1993',
        'Publisher': 'Audioworks',
        'Image_URL': 'http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 15.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '679425608',
        'Book_Title': 'Under the Black Flag: The Romance and the Reality of Life Among the Pirates',
        'Book_Author': 'David Cordingly',
        'Description': 'A true story of pirates and piracy.',
        'Year_Of_Publication': '1996',
        'Publisher': 'Random House',
        'Image_URL': 'http://images.amazon.com/images/P/0679425608.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 20.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '074322678X',
        'Book_Title': 'Where You\'ll Find Me: And Other Stories',
        'Book_Author': 'Ann Beattie',
        'Description': 'A collection of short stories.',
        'Year_Of_Publication': '2002',
        'Publisher': 'Scribner',
        'Image_URL': 'http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 16.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '771074670',
        'Book_Title': 'Nights Below Station Street',
        'Book_Author': 'David Adams Richards',
        'Description': 'A poignant exploration of life in a small town.',
        'Year_Of_Publication': '1988',
        'Publisher': 'Emblem Editions',
        'Image_URL': 'http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 17.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '080652121X',
        'Book_Title': 'Hitler\'s Secret Bankers: The Myth of Swiss Neutrality During the Holocaust',
        'Book_Author': 'Adam Lebor',
        'Description': 'A deep dive into Swiss banking during WWII.',
        'Year_Of_Publication': '2000',
        'Publisher': 'Citadel Press',
        'Image_URL': 'http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 23.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '887841740',
        'Book_Title': 'The Middle Stories',
        'Book_Author': 'Sheila Heti',
        'Description': 'A collection of short stories about life and relationships.',
        'Year_Of_Publication': '2004',
        'Publisher': 'House of Anansi Press',
        'Image_URL': 'http://images.amazon.com/images/P/0887841740.01.LZZZZZZZ.jpg',
        'category': 'Fiction',
        'price': 21.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '1552041778',
        'Book_Title': 'Jane Doe',
        'Book_Author': 'R. J. Kaiser',
        'Description': 'A gripping mystery novel.',
        'Year_Of_Publication': '1999',
        'Publisher': 'Mira Books',
        'Image_URL': 'http://images.amazon.com/images/P/1552041778.01.LZZZZZZZ.jpg',
        'category': 'Mystery',
        'price': 19.49,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '1558746218',
        'Book_Title': 'A Second Chicken Soup for the Woman\'s Soul',
        'Book_Author': 'Jack Canfield',
        'Description': 'Inspirational stories for women.',
        'Year_Of_Publication': '1998',
        'Publisher': 'Health Communications',
        'Image_URL': 'http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg',
        'category': 'Self-Help',
        'price': 15.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '1580630852',
        'Book_Title': 'The Unabridged Journals of Sylvia Plath',
        'Book_Author': 'Sylvia Plath',
        'Description': 'The complete journals of Sylvia Plath.',
        'Year_Of_Publication': '2000',
        'Publisher': 'Anchor',
        'Image_URL': 'http://images.amazon.com/images/P/1580630852.01.LZZZZZZZ.jpg',
        'category': 'Biography',
        'price': 28.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '8480451181',
        'Book_Title': 'Guns, Germs, and Steel: The Fates of Human Societies',
        'Book_Author': 'Jared Diamond',
        'Description': 'An exploration of the factors that shape civilizations.',
        'Year_Of_Publication': '1999',
        'Publisher': 'W. W. Norton & Company',
        'Image_URL': 'http://images.amazon.com/images/P/8480451181.01.LZZZZZZZ.jpg',
        'category': 'History',
        'price': 25.50,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780060925401',
        'Book_Title': 'The Hitchhiker\'s Guide to the Galaxy',
        'Book_Author': 'Douglas Adams',
        'Description': 'A comedic science fiction adventure.',
        'Year_Of_Publication': '1979',
        'Publisher': 'Pan Books',
        'Image_URL': 'http://images.amazon.com/images/P/9780060925401.01.LZZZZZZZ.jpg',
        'category': 'Science Fiction',
        'price': 14.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780375838475',
        'Book_Title': 'Harry Potter and the Sorcerer\'s Stone',
        'Book_Author': 'J.K. Rowling',
        'Description': 'The first book in the Harry Potter series.',
        'Year_Of_Publication': '1997',
        'Publisher': 'Scholastic Inc.',
        'Image_URL': 'http://images.amazon.com/images/P/9780375838475.01.LZZZZZZZ.jpg',
        'category': 'Fantasy',
        'price': 10.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780451524935',
        'Book_Title': '1984',
        'Book_Author': 'George Orwell',
        'Description': 'A dystopian novel about totalitarianism.',
        'Year_Of_Publication': '1949',
        'Publisher': 'Signet Classics',
        'Image_URL': 'http://images.amazon.com/images/P/9780451524935.01.LZZZZZZZ.jpg',
        'category': 'Dystopian',
        'price': 9.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780140449242',
        'Book_Title': 'The Brothers Karamazov',
        'Book_Author': 'Fyodor Dostoevsky',
        'Description': 'A philosophical novel exploring faith and doubt.',
        'Year_Of_Publication': '1880',
        'Publisher': 'Penguin Classics',
        'Image_URL': 'http://images.amazon.com/images/P/9780140449242.01.LZZZZZZZ.jpg',
        'category': 'Classic',
        'price': 12.50,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780452284234',
        'Book_Title': 'The Great Gatsby',
        'Book_Author': 'F. Scott Fitzgerald',
        'Description': 'A novel about the American Dream in the 1920s.',
        'Year_Of_Publication': '1925',
        'Publisher': 'Plume',
        'Image_URL': 'http://images.amazon.com/images/P/9780452284234.01.LZZZZZZZ.jpg',
        'category': 'Classic',
        'price': 14.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9780143132294',
        'Book_Title': 'Becoming',
        'Book_Author': 'Michelle Obama',
        'Description': 'A memoir by the former First Lady of the United States.',
        'Year_Of_Publication': '2018',
        'Publisher': 'Crown Publishing Group',
        'Image_URL': 'http://images.amazon.com/images/P/9780143132294.01.LZZZZZZZ.jpg',
        'category': 'Biography',
        'price': 24.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9781501160466',
        'Book_Title': 'The Silent Patient',
        'Book_Author': 'Alex Michaelides',
        'Description': 'A psychological thriller about a woman who stops speaking.',
        'Year_Of_Publication': '2019',
        'Publisher': 'Celadon Books',
        'Image_URL': 'http://images.amazon.com/images/P/9781501160466.01.LZZZZZZZ.jpg',
        'category': 'Thriller',
        'price': 15.99,
        'created_at': '2024-10-08T12:00:00'
    },
    {
        'ISBN': '9781538700328',
        'Book_Title': 'Educated: A Memoir',
        'Book_Author': 'Tara Westover',
        'Description': 'A memoir about a woman who grows up in a strict and abusive household in rural Idaho.',
        'Year_Of_Publication': '2018',
        'Publisher': 'Random House',
        'Image_URL': 'http://images.amazon.com/images/P/9781538700328.01.LZZZZZZZ.jpg',
        'category': 'Biography',
        'price': 18.99,
        'created_at': '2024-10-08T12:00:00'
    }
]
